#!/bin/bash
# Script para instalar Apache Web Server
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
echo "<h1>Hello World desde $(hostname -f)</h1>" > /var/www/html/index.html
